version: "3.5"
services:
    aspen-dev-box:
        image: registry.gitlab.com/aspen-discovery/aspen-dev-box-image/aspen-dev-box:debug
        volumes:
            - '$ASPEN_CLONE:/usr/local/aspen-discovery'
            - '$ASPEN_DOCKER/site/:/usr/local/aspen-discovery/sites/test.localhostaspen'
            - '$ASPEN_DOCKER/etc/apache2/sites-enabled:/etc/apache2/sites-enabled'
            - '$ASPEN_DOCKER/site/conf/crontab_settings.txt:/etc/cron.d/cron'
            - "$ASPEN_DOCKER/aliases:/root/.bashrc"
            - '$ASPEN_DOCKER/error_reporting.ini:/etc/php/8.0/apache2/conf.d/error_reporting.ini'
            - '$ASPEN_DOCKER/xdebug.ini:/etc/php/8.0/apache2/conf.d/xdebug.ini'
        ports:
            - '8084:8080'
            - '8083:80'
        container_name: containeraspen
        networks:
          - koha_kohanet
        platform: linux/x86_64
        tty: true
        environment:
          - WSL_IP
        extra_hosts: 
              - host.docker.internal:${WSL_IP:-host-gateway} 
  aspendb:
    container_name: aspen-db
    environment:
      - MYSQL_ROOT_PASSWORD=aspen
      - MYSQL_DATABASE:aspen
      - MYSQL_USER:aspensuper
      - MYSQL_PASSWORD:aspensuper
      - MYSQL_TCP_PORT:7000
    image: "mariadb"
    volumes:
      - $ASPEN_DOCKER/setup.sql:/docker-entrypoint-initdb.d/init-script.sql
      - $ASPEN_DOCKER/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-paspen", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - koha_kohanet
    platform: linux/x86_64

networks:
  koha_kohanet:
    name: koha_kohanet
    external: true
